# Generated by Django 4.2.6 on 2023-10-16 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp01', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='wrtier',
            new_name='writer',
        ),
    ]
